server:
  error:
    include-stacktrace: never

    include-message: always

spring:
  application:
    name: springboot2-essentials
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
      
management:
        endpoints:
          web:
            exposure:
              include: info, health, metrics, prometheus
              
info:
  app: Spring boot 2 Essentials by devdojo
  website: https://devdojo.academy